Kotlin rewrite
wingio/plugins pull request #34
Opened 2022-03-27 10:19 UTC by autodistries

Idfk how that works :trollface: sorry

2022-03-27 13:19 UTC, wingio commented
i don't really want the share button replaced, the current position of the copy message link option is already muscle memory

2022-03-27 19:00 UTC, autodistries commented
Aw

2022-03-27 19:00 UTC, autodistries commented
Well, settings time then ig

2022-03-27 19:01 UTC, autodistries commented
Idk if when i have time tho. I'll tell you if i do

2022-04-02 18:48 UTC, autodistries commented
that is done and cool

2022-04-02 18:49 UTC, wingio commented
you need to fix some of the package names

2022-04-02 18:51 UTC, wingio commented
also keep the old plugin description and fix the version number

2022-04-02 18:52 UTC, wingio commented
and the link icon should be ic_diag_link_24dp

2022-04-02 19:00 UTC, autodistries commented
did do

2022-04-03 23:29 UTC, wingio requested changes

2022-04-03 23:29 UTC, wingio commented on MessageLinkContext/src/main/java/xyz/wingio/plugins/MessageLinkContext.kt
> +                                var guildId = StoreStream.getChannels().getChannel(msg.channelId).h().toString()
use [ChannelWrapper](https://github.com/Aliucord/Aliucord/blob/main/Aliucord/src/main/java/com/aliucord/wrappers/ChannelWrapper.kt)

2022-04-03 23:29 UTC, wingio commented on MessageLinkContext/src/main/java/xyz/wingio/plugins/MessageLinkContext.kt
> +                    linearLayout.addView(copyMessageUrl, 13)
Make the position 6

2025-09-17 06:34 UTC, closed without merging